name: WakaTime Stats  
on:
  schedule:
    - cron: '0 5 * * *'  
  workflow_dispatch:  

jobs:
  update-readme:
    name: Update WakaTime Stats  
    runs-on: ubuntu-latest  
    steps:
        # this action name
      - uses: athul/waka-readme@master # do NOT replace with anything else
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }} # required
          API_BASE_URL: https://wakatime.com/api # optional
          REPOSITORY: JLi2007/JLi2007 # optional
